# Generated by Django 5.2.3 on 2025-07-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_adminprofile_department_teacherprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='qualification',
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject_taught',
            field=models.JSONField(default=list),
        ),
    ]
