# Generated by Django 5.2.3 on 2025-07-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_teacherprofile_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='employee_id',
        ),
    ]
