# Generated by Django 5.2.3 on 2025-07-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0002_tenantuser_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_app.school'),
        ),
    ]
