# Generated by Django 5.2.3 on 2025-07-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0003_alter_tenantuser_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='school',
        ),
    ]
