# Generated by Django 5.2.3 on 2025-07-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0004_remove_tenantuser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public_app.school'),
        ),
    ]
